// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SOCATemplate.Infrastructure.Persistence;

#nullable disable

namespace SOCATemplate.DbMigration.SQLite.Migrations
{
    [DbContext(typeof(SOCATemplateDbContext))]
    [Migration("20211130210951_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("SOCATemplate.Application.Common.Entities.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("tbl_User", "dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
